CREATE TABLE Users 
  ( 
     id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name     VARCHAR(16) NOT NULL UNIQUE,
     password VARCHAR(32) NOT NULL 
  ); 

CREATE TABLE Messages
  ( 
     id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     senderid   INTEGER NOT NULL, 
     receiverid INTEGER NOT NULL, 
     message    VARCHAR(255) NOT NULL, 
     timestamp  TIMESTAMP NOT NULL 
  ); 